namePrefix: kustomize-

resources:
  - github.com/leoryu/argocd-example-apps/kustomize-guestbook
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: patch.yaml
    target:
      kind: Service
